services:
    postgres:
        image: postgres
        restart: always
        ports:
            - 5432
        environment:
            POSTGRES_DB: my_store
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
        volumes:
            - ./postgres_data:/var/lib/postgresql/data